services:
  sp-monitor:
    image: ghcr.io/wx2cyj/dc-jk:latest
    container_name: sp-tobacco-monitor
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
